workflows:
  build_expo_ios:
    name: Build Expo iOS App
    environment:
      node: latest
      groups:
        - deloy
    scripts:
      # Cài đặt EAS CLI
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          yarn install
      
      # Đăng nhập vào Expo (dùng token)
      - name: Login to Expo
        script: |
    echo $EXPO_TOKEN | eas login --token
      
      # Build ứng dụng iOS
      - name: Build iOS app
        script: eas build -p ios --non-interactive

    artifacts:
      - build/**/*
    publishing:
      email:
        recipients:
          - cminh24dz@gmail.com
