workflows:
  build_expo_ios:
    name: Build Expo iOS App
    environment:
      node: latest
      groups:
        - deploy
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          yarn install
      
      - name: Login to Expo
        script: |
          echo "$EXPO_TOKEN" | eas login --token
      
      - name: Build iOS app
        script: eas build -p ios --non-interactive

    artifacts:
      - build/**/*
    publishing:
      email:
        recipients:
          - cminh24dz@gmail.com