workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - account  # Các nhóm biến môi trường có thể cần
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
          # Cài đặt dependencies của dự án React Native

      - name: Build iOS app
        script: |
          expo build:ios --no-wait --release-channel production
          # Build ứng dụng iOS
