workflows:
  ios-workflow:
    name: Build iOS App
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN # Thay bằng token Expo của bạn
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build iOS App
        script: |
          eas build --platform ios --profile development
    artifacts:
      - output/*.ipa
