workflows:
  workflow-name:
    name: Example Workflow
    environment:
      groups:
        - account  # Đặt tên nhóm môi trường
    scripts:
      - name: Install dependencies
        script: |
          npm install
          # Cài đặt các dependencies của dự án

      - name: Build iOS app
        script: |
          expo build:ios --no-wait --release-channel production
          # Build ứng dụng iOS
