workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      node: 18.x
      xcode: latest
    scripts:
      - name: Install Expo CLI
        script: npm install -g expo-cli
      
      - name: Install dependencies
        script: npm install
      
      - name: Prebuild Expo
        script: npx expo prebuild --clean
      
      - name: Build iOS
        script: npx eas build -p ios --non-interactive
