workflows:
  react-native-expo:
    name: Build Expo App for iOS
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN # Đặt token Expo của bạn ở đây
    scripts:
      - name: Install dependencies
        script: npm install
      - name: EAS Build for iOS
        script: |
          eas build --platform ios --profile development
    artifacts:
      - output/*.ipa
