workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        EAS_PROJECT_ID: "97b0c6d5-93eb-4802-bd2f-62a3417a660d"
      groups:
        - account
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli eas-cli
          npm install
      - name: Prebuild Expo
        script: |
          npx expo prebuild
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build iOS app
        script: |
          eas build -p ios --profile release
