workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      node: 20.11.1
      xcode: latest
    scripts:
      - name: Install global dependencies
        script: |
          npm install -g npm@latest
          npm install -g expo-cli
          npm install -g eas-cli
      
      - name: Install project dependencies
        script: npm ci

      - name: Log in to Expo
        script: |
          if [ -n "$EXPO_TOKEN" ]; then
            echo "Using EXPO_TOKEN for authentication"
          else
            eas login --username $EXPO_USERNAME --password $EXPO_PASSWORD
          fi

      - name: Build iOS
        script: npx eas build -p ios --non-interactive
