workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        EXPO_CLI_VERSION: 5.x
    scripts:
      - npm install -g expo-cli
      - expo prebuild --clean
      - eas build:configure
      - eas build -p ios --non-interactive