workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        EXPO_CLI_VERSION: 5.x
    scripts:
      - npm install -g expo-cli
      - expo prebuild --clean
      - eas build:configure
      - eas build -p ios --non-interacworkflows:
  ios-expo-build:
    name: iOS Expo Build
    environment:
      node: 18.x
      xcode: latest
      vars:
        EXPO_CLI_VERSION: latest
    scripts:
      - name: Install Expo CLI
        script: npm install -g expo-cli

      - name: Install dependencies
        script: npm install

      - name: Prebuild Expo
        script: expo prebuild --clean

      - name: Configure EAS
        script: |
          npm install -g eas-cli
          eas build:configure

      - name: Build iOS
        script: eas build -p ios --non-interactive
    when:
      branch:
        - main
        - mastertive