workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - account  # Các nhóm biến môi trường nếu cần
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo  # Cài đặt expo CLI mới
          npm install          # Cài đặt dependencies của dự án, bao gồm react-native

      - name: Install EAS CLI
        script: |
          npm install -g eas-cli  # Cài đặt EAS CLI

      - name: Build iOS app with EAS
        script: |
          eas build -p ios --profile production  # Sử dụng EAS để build ứng dụng iOS
