workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      node: 18.x
      xcode: latest
      vars:
        EXPO_CLI_VERSION: latest
    scripts:
      - name: Install Expo CLI
        script: npm install -g expo-cli
      
      - name: Install dependencies
        script: npm install
      
      - name: Login to Expo
        script: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      
      - name: Prebuild Expo
        script: npx expo prebuild --clean
      
      - name: Configure EAS
        script: npx eas-cli build:configure
      
      - name: Build iOS
        script: npx eas build -p ios --non-interactive
    triggers:
      - push:
          branches:
            - main
            - master
